app/models/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

migrate = Migrate()

db = SQLAlchemy()

app/models/users/models.py
from flask import current_app
from app.models.models import db
from sqlalchemy.sql import func
from itsdangerous import (TimedJSONWebSignatureSerializer
                          as Serializer, BadSignature, SignatureExpired)
import bcrypt

roles = db.Table(
    'roles',
    db.Column(
        'user_id', db.Integer,
        db.ForeignKey('user.id'),
        primary_key=True
    ),
    db.Column(
        'role_id',
        db.Integer,
        db.ForeignKey('role.id'),
        primary_key=True
    )
)


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(80), unique=True, nullable=False)
    password_hash = db.Column(db.String(80), nullable=False)
    created_date = db.Column(
        db.DateTime(timezone=True),
        server_default=func.now()
    )
    updated_date = db.Column(db.DateTime(timezone=True), onupdate=func.now())

    @property
    def password(self):
        raise AttributeError('password not readable')

    @password.setter
    def password(self, password):
        self.password_hash = bcrypt.hashpw(
            password.encode('utf8'), bcrypt.gensalt()
        )

    def verify_password(self, password):
        return bcrypt.checkpw(password.encode('utf8'), self.password_hash.encode('utf8'))

    def __repr__(self):
        return f'<User {self.username}>'

    def get_id(self):
        return self.id

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False
    
    def generate_auth_token(self, expiration=600):
        s = Serializer(current_app.config.get('SECRET_KEY'), expires_in=expiration)
        return s.dumps({'id': self.id})

    @staticmethod
    def verify_auth_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except SignatureExpired:
            return None # valid token, but expired
        except BadSignature:
            return None # invalid token
        user = User.query.get(data['id'])
        return user

class Role(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    users = db.relationship(
        "User",
        secondary=roles
    )

app/blueprints/admin/admin_blueprint.py
from flask import Blueprint, render_template
# import app.models.users.models as Users
# from app.models.models import db
from flask_login import login_required, current_user

admin_bp = Blueprint('admin', __name__)


@admin_bp.before_request
@login_required
def before_request():
    pass


@admin_bp.route('/')
def dashboard():
    data = {
        "contentTitle": "This is a Title",
        "subContentTitle": "SubContentTitle",
        "cardTitle": "This is cardTitle",
        "username":  current_user.username
    }
    return render_template('dashboard.html', data=data)

app/blueprints/login/login_blueprint.py
from flask import Blueprint, render_template, redirect, url_for
import app.models.users.models as Users
from app.models.models import db
from flask_login import login_required, login_user, logout_user

login_bp = Blueprint('login', __name__)


@login_bp.route('/')
@login_bp.route('/login', methods=['GET', 'POST'])
def login():
    user = db.session.query(Users.User)\
        .filter(Users.User.username == "admin1")\
        .first()
    if user:
        if user.verify_password('123456789abc'):
            login_user(user)
    return render_template('login.html')


@login_bp.route('/create')
def createUser():
    try:
        user1 = Users.User(
            username="admin1",
            email="admin1@localhost",
            password="123456789abc"
        )
        # Creates new role
        # role = Users.Role(name="admin")

        # Use existing role to assign to user
        role = db.session.query(Users.Role)\
            .filter(Users.Role.name == 'admin')\
            .first()
        role.users.append(user1)
        db.session.add(role)
        db.session.commit()
    except Exception as error:
        print(error)

    return "OK", 200


@login_bp.route('/logout')
@login_required
def logoutUser():
    logout_user()
    return redirect(url_for('login.login'))

app/templates/admin_base.html
{% set appName = applicationData.appName if applicationData and applicationData.appName else "appName missing in data" %}
{% set contentTitle = data.contentTitle if data and data.contentTitle else "contentTitle missing in data" %}
{% set subContentTitle = data.subContentTitle if data and data.subContentTitle else "" %}
{% set cardTitle = data.cardTitle if data and data.cardTitle else "cardTitle missing in data" %}
{% set cardStyle = data.cardStyle if data and data.cardStyle else "card-default" %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% include "partials/head.html" %}
        <script src="{{ url_for('static', filename='js/jquery.validate.min.js')}}"></script>
        <script src="{{ url_for('static', filename='js/adminlte.js')}}"></script>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/all.min.css')}}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/adminlte.css')}}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
        <title>{% block title %}{{appName}}{% endblock %}</title>
    {% endblock %}
</head>
<body>
  <div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>

      </ul>
  
      <!-- Right navbar links -->
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button"><i
              class="fas fa-th-large"></i></a>
        </li>
      </ul>
    </nav>
    <!-- /.navbar -->
  
    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
      <!-- Brand Logo -->
      <a href="index3.html" class="brand-link">
        <span class="brand-text font-weight-light">{{appName}}</span>
      </a>
  
      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar Menu -->
          <ul class="nav nav-pills nav-sidebar flex-column mt-2" data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-item has-treeview {{'menu-open' if uploadActive else ''}}">
              <a href="#" class="nav-link {{'active' if uploadActive else ''}}">
                  <img src="{{url_for('static', filename='images/avatars/default_avatar.gif')}}" alt="" class="img-circle elevation-2">
                <p style="vertical-align: middle;">
                {{data.username.capitalize()}}
                <i class="center-right right fas fa-angle-left"></i>
              </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a href="/logout" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                      Logout
                    </p>
                  </a>
                </li>
              </ul>
            </li>
          
          </ul>
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                 with font-awesome or any other icon font library -->
                 
                 <li class="nav-header">
                   General
                 </li>
                 <li class="nav-item">
                   <a href="{{url_for('admin.dashboard', _external=True)}}" class="nav-link {{'active' if dashboardActive else ''}}">
                     <i class="nav-icon fas fa-tachometer-alt"></i>
                     <p>
                       Dashboard
                     </p>
                   </a>
                 </li>
                 <li class="nav-item">
                  <a href="#" class="nav-link {{'active' if hardwareActive else ''}}">
                    <i class="nav-icon fas fa-server"></i>
                    <p>
                      Hardware
                    </p>
                  </a>
                </li>
                <li class="nav-item has-treeview {{'menu-open' if uploadActive else ''}}">
                  <a href="#" class="nav-link {{'active' if uploadActive else ''}}">
                    <i class="nav-icon fas fa-upload"></i>
                    <p>
                      Upload hardware
                      <i class="right fas fa-angle-left"></i>
                    </p>
                  </a>
                  <ul class="nav nav-treeview">
                    <li class="nav-item">
                      <a href="" class="nav-link {{'active' if uploadType and uploadType == 'stb' else ''}}">
                        <i class="far fa-circle nav-icon"></i>
                        <p>
                          STB
                        </p>
                      </a>
                    </li>
                  </ul>
                </li>
          </ul>
        </nav>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>
  
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">{{contentTitle}}</h1>
              <small>{{subContentTitle}}</small>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item">{{contentTitle}}</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->
  
      <!-- Main content -->
      <div class="content">
        <div class="container-fluid">
          <div class="card {{cardStyle}}">
            <div class="card-header">
              <h3 class="card-title">
                  {{cardTitle}}
              </h3>
              <div class="card-tools">
                <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                  <i class="fas fa-minus"></i></button>
              </div>
            </div>
            <div class="card-body">
              {% block content %}
              {% endblock %}
            </div>
          </div>
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
  
    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
      <div class="p-3">
        <h5>Title</h5>
        <p>Sidebar content</p>
      </div>
    </aside>
    <!-- /.control-sidebar -->
  
    <!-- Main Footer -->
    <footer class="main-footer">
      <!-- Default to the left -->
      <strong>Copyright &copy;  <a href="{{url_for('login.login', _external=True)}}">{{appName}}</a>.</strong> All rights reserved.
    </footer>
  </div>
  <!-- ./wrapper -->
</body>
</html>

app/templates/dashboard.html
{% extends "admin_base.html" %}
{% set dashboardActive = true %}

{% block content %}
    <p class="important">
      Welcome to my awesome homepage.
    </p>
{% endblock %}

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "partials/head.html" %}
    <script src="{{ url_for('static', filename='js/tempLogin.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/signin.css') }}">
</head>
<body>
    <div class="container">
      <nav class="navbar navbar-expand-sm bg-light navbar-light justify-content-end">
        <a class="navbar-brand" href="#">None</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse flex-grow-0 ml-auto mr-1" id="navbarSupportedContent">
            <ul class="navbar-nav text-right">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Register</a>
                </li>
            </ul>
        </div>
    </nav>
    </div>
    <div class="container text-center">
      <form class="form-signin" id="signin">
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox mb-3">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>
    </div>
</body>
</html>

app/templates/partials/head.html
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
<script src="{{ url_for('static', filename='js/jquery-3.5.0.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>